export const subject_register = 'Su usuario fue registrado con exito';
export const html_register =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #0000; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff ;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Bienvenido a Nuestro Servicio</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por registrarte en nuestro servicio. Estamos encantados de tenerte a bordo.</p><p>Para empezar, por favor verifica tu correo electrónico haciendo clic en el siguiente botón:</p><a href="http://example.com/verificar" class="button">Verificar Correo</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expresso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expresso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_order = 'Tu orden se realizo con exito';
export const html_order =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #0000; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff ;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Tu Orden</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por preferirnos.</p><p>Para saber mas información con respecto orden o ver la factura puedes undir el siguiente boton:</p><a href="http://example.com/verificar" class="button">Pedido</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expresso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expresso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_status = 'Informacion sobre tu pedido';
export const html_status =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #0000; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff ;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Tu pedido</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por usar nuestro servicio. Estamos encantados de ayudarte.</p><p>Para tener mas informacion hacerca de tu pedido puedes undir el siguiente boton:</p><a href="http://example.com/verificar" class="button">Ver estado del pedido</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expresso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expresso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_updateUser = 'Tu informacion personal ha sido actualizada';
export const html_updateUser =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #0000; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff ;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Actualizacion de informacion</h1></div><div class="content"><h2>Hola,</h2><p>Hemos detectado que haz hecho un cambio en tu infrmación de usuario</p><br/><p>Si no fuiste tu porfavor comunicate con nostros, de no ser así puedes hacer caso omiso a este correo<a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expresso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expresso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';