export const subject_register = 'Su usuario fue registrado con exito';
export const html_register =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff; color: #CB1B1A;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Bienvenido a Expreso Rivadavia</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por registrarte en nuestro servicio. Estamos encantados de tenerte a bordo.</p><p>Para empezar, por favor verifica que tu información sea correcta haciendo clic en el siguiente botón:</p><a href="https://expresorivadavia.vercel.app/dashboard" class="button">Tu Usuario</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expreso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expreso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_order = 'Tu orden se realizo con exito';
export const html_order =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff; color: #CB1B1A;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Tu Orden</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por preferirnos.</p><p>Para saber más información con respecto a tu orden, pulsa el siguiente botón:</p><a href="https://expresorivadavia.vercel.app/dashboard/shipments" class="button">Mis Ordenes</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expreso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expreso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_status = 'Informacion sobre tu envío';
export const html_status =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff; color: #CB1B1A;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Tu Orden</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por preferirnos.</p><p>El estado de tu orden ha sido actualizado. Para saber más información con respecto a tu orden, pulsa el siguiente botón:</p><a href="https://expresorivadavia.vercel.app/dashboard/shipments" class="button">Mis Ordenes</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expreso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expreso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_updateUser = 'Tu informacion personal ha sido actualizada';
export const html_updateUser =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff; color: #CB1B1A;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Tu Usuario fue actualizado</h1></div><div class="content"><h2>Hola,</h2><p>Haz cambiado datos de tu usuario.</p><p>Algunos datos de tu usuario fueron actualizados recientemente. Para saber más información con respecto a tu usuario, pulsa el siguiente botón:</p><a href="https://expresorivadavia.vercel.app/dashboard" class="button">Mi Usuario</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expreso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expreso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_reviewUs = 'Tu envío fue entregado, califícanos!';
export const html_reviewUs =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff; color: #CB1B1A;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Recibiste tu pedido</h1></div><div class="content"><h2>Hola,</h2><p>Gracias por preferirnos.</p><p>El pedido ha sido entregado con éxito. Te invitamos a que califiques el servicio que te brindamos. Para calificar tu pedido, pulsa el siguiente botón:</p><a href="https://expresorivadavia.vercel.app/reviews" class="button">Califícanos</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expreso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expreso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_promotional =
  'Descuento para tu próximo envío en Expreso Rivadavia';
export const html_promotional =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #CB1B1A; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #CB1B1A;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #CB1B1A; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #ffffff; color: #CB1B1A;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Información únicamente para ti</h1></div><div class="content"><h2>Hola,</h2><p>Sabemos que necesitas enviar algo.</p><p>Te enviamos este correo para notificar que hoy enviaremos los pedidos más rápido. Para realizar un pedido, pulsa el siguiente botón:</p><a href="https://expresorivadavia.vercel.app/new-shipment" class="button">Haz tu pedido</a><p>Si tienes alguna pregunta, no dudes en <a href="expresorivadaviainfo@gmail.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Expreso Rivadavia</p></div><div class="footer"><p>&copy; 2024 Expreso Rivadavia. Todos los derechos reservados.</p></div></div></body></html>';
