export const subject_register = 'Su usuario fue registrado con exito';
export const html_register =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #007BFF; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #007BFF;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #007BFF; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #0056b3;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Bienvenido a Nuestro Servicio</h1></div><div class="content"><h2>Hola, Juan Pérez</h2><p>Gracias por registrarte en nuestro servicio. Estamos encantados de tenerte a bordo.</p><p>Para empezar, por favor verifica tu correo electrónico haciendo clic en el siguiente botón:</p><a href="http://example.com/verificar" class="button">Verificar Correo</a><p>Si tienes alguna pregunta, no dudes en <a href="mailto:support@example.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Mi Compañía</p></div><div class="footer"><p>&copy; 2024 Mi Compañía. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_order = 'Tu orden se realizo con exito';
export const html_order =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #007BFF; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #007BFF;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #007BFF; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #0056b3;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Bienvenido a Nuestro Servicio</h1></div><div class="content"><h2>Hola, Juan Pérez</h2><p>Gracias por registrarte en nuestro servicio. Estamos encantados de tenerte a bordo.</p><p>Para empezar, por favor verifica tu correo electrónico haciendo clic en el siguiente botón:</p><a href="http://example.com/verificar" class="button">Verificar Correo</a><p>Si tienes alguna pregunta, no dudes en <a href="mailto:support@example.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Mi Compañía</p></div><div class="footer"><p>&copy; 2024 Mi Compañía. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_status = 'Informacion sobre tu pedido';
export const html_status =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #007BFF; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #007BFF;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #007BFF; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #0056b3;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Bienvenido a Nuestro Servicio</h1></div><div class="content"><h2>Hola, Juan Pérez</h2><p>Gracias por registrarte en nuestro servicio. Estamos encantados de tenerte a bordo.</p><p>Para empezar, por favor verifica tu correo electrónico haciendo clic en el siguiente botón:</p><a href="http://example.com/verificar" class="button">Verificar Correo</a><p>Si tienes alguna pregunta, no dudes en <a href="mailto:support@example.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Mi Compañía</p></div><div class="footer"><p>&copy; 2024 Mi Compañía. Todos los derechos reservados.</p></div></div></body></html>';

export const subject_updateUser = 'Tu informacion personal ha sido actualizada';
export const html_updateUser =
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><style>body {font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0;} .container {max-width: 600px; margin: 20px auto; background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);} .header {text-align: center; padding: 20px 0; background-color: #007BFF; color: #ffffff; border-radius: 8px 8px 0 0;} .header h1 {margin: 0; font-size: 24px;} .content {padding: 20px; line-height: 1.6; color: #333333;} .content h2 {color: #007BFF;} .button {display: inline-block; padding: 10px 20px; margin: 10px 0; font-size: 16px; color: #ffffff; background-color: #007BFF; border-radius: 5px; text-decoration: none; text-align: center;} .button:hover {background-color: #0056b3;} .footer {text-align: center; padding: 10px; font-size: 14px; color: #666666; border-top: 1px solid #dddddd; margin-top: 20px;} </style></head><body><div class="container"><div class="header"><h1>Bienvenido a Nuestro Servicio</h1></div><div class="content"><h2>Hola, Juan Pérez</h2><p>Gracias por registrarte en nuestro servicio. Estamos encantados de tenerte a bordo.</p><p>Para empezar, por favor verifica tu correo electrónico haciendo clic en el siguiente botón:</p><a href="http://example.com/verificar" class="button">Verificar Correo</a><p>Si tienes alguna pregunta, no dudes en <a href="mailto:support@example.com">contactar con nosotros</a>.</p><p>¡Gracias!</p><p>El equipo de Mi Compañía</p></div><div class="footer"><p>&copy; 2024 Mi Compañía. Todos los derechos reservados.</p></div></div></body></html>';
